### ISSUE TITLE
Would love if you can also have links for the problems you solve.

### ISSUE THREAD

**Issue by 0xatulpatil** [unikdahal/TLE-Eliminators#1]

**Comment by unikdahal** [comment]
I have attached the question list in questions.txt file starting from Week 1

**Comment by 0xatulpatil** [comment]
Ohh, I completely missed it. I Was looking in the week 2 section. 

First of all thanks for writing and documenting your coursework, I could not afford the course but your repo will undoubtedly help me a lot.

I've they also have daily questions that they give to candidates to solve, would love to follow along with you on those questions as well. 

It's completely fine if you don't want to share those questions with me, I understand that you have paid your hard-earned money for the course and would not want to give away those questions to random strangers on the internet.

**Comment by unikdahal** [comment]
Connect with me on any social media platform will share something useful with you

I think my profile has some social links

**Comment by 0xatulpatil** [comment]
Went through your twitter, but your DM's are closed.

**Comment by 0xatulpatil** [comment]
you can delete/close this issue now
